### PR TITLE
Replaces console.log by throw by semantic issues, cleaning and code comp...

### PR DESCRIPTION
**Pull request by dayvsonlima**
Replaces console.log by throw by semantic issues, cleaning and code compatibility

It is best to use the launch of exeções with throw the console.log that is not compatible with older browsers

### CODE REVIEW

**Comment by tulios** [comment]
Hi @dayvsonlima I agree with you about the semantics, however this change will result in broken code out there, since an uncaught exception will break other code in the page. About the code compatibility with older browsers, the use of `console.log` is wrapped by an existence check therefore it's not really a problem. I want the opinion of my co-workers about it, what do you think @danielfm, @ggarnier and @emerleite ?

**Comment by ggarnier** [comment]
@tulios I agree with you. Throwing an exception is dangerous, as it might break other code. Besides, older browsers that don't support `console.log` won't break, they just don't output the error message.

**Comment by dayvsonlima** [comment]
As to break the application I could understand the need. Within this approach agree with @ggarnier 

To maintain the semantics I suggest then that the console.log is replaced by a console.warn, what do you think @tulios ?

**Comment by tulios** [comment]
@dayvsonlima I think it will be a good idea, could you create another pull request with that change?

**Comment by dayvsonlima** [comment]
of course! @tulios

**Comment by dayvsonlima** [comment]
https://github.com/globocom/responsive-hub/pull/3

**Pull request closed without merging**
